### ISSUE TITLE
New translation: brazilian portuguese

### ISSUE THREAD

**Issue by Felipefpl** [AM2R-Community-Developers/AM2R-Localizations#7]
Hi, i did this translation for am2r, it's fully done and i reviewed through several dictionaries. I wanted to report that the GUI needs to be redone because most of times the portuguese words are bigger than the words in english language, the GUI cant fully display the words/phrases in several places.

Also, the fonts are hard to see, it would be good if the fonts didnt have jagged borders. 

[brazilian portuguese.zip](https://github.com/AM2R-Community-Developers/AM2R-Localizations/files/6359904/brazilian.portuguese.zip)

**Comment by Miepee** [comment]
Hi there!
Could you create a Pull request instead of opening an issue?

**Comment by Felipefpl** [comment]
I tried to find a place in the pull request area to send my file but i didnt see one so i uploaded it here.

**Comment by Felipefpl** [comment]
@Miepee 

Thank you very much for teaching me how to do a pull request, i did it.
